# This GitHub Actions workflow customizes server-ci-artifacts.yml.
# The differences from server-ci-artifacts.yml are as follows:
# - It uploads container images to Google Cloud Artifact Registry instead of Docker Hub.
# - It does not upload build artifacts to S3.
# - It is triggered by pushes to Git tags that start with 'v'.
name: Custom Ci Artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'
      tag:
        description: 'Tag to build'
        required: false
        default: ''

jobs:
  build-artifacts:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && (inputs.branch || inputs.tag) || github.ref }}

      - name: Calculate Golang Version
        id: go
        run: echo GO_VERSION=$(cat .go-version) >> "${GITHUB_OUTPUT}"

      - name: Setup Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ steps.go.outputs.GO_VERSION }}
          cache-dependency-path: |
            server/go.sum
            server/public/go.sum

      - name: ci/setup-node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        id: setup_node
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: "webapp/package-lock.json"

      - name: Run setup-go-work
        run: make setup-go-work

      - name: Build
        run: |
          make config-reset
          make build-cmd BUILD_NUMBER='${GITHUB_HEAD_REF}-${GITHUB_RUN_ID}'
          make package BUILD_NUMBER='${GITHUB_HEAD_REF}-${GITHUB_RUN_ID}'

      # In server-ci-artifacts.yml, this step uploads the artifacts to S3.
      # Here, we place the artifacts in a directory that will be used by the next job.
      - name: Upload Mattermost Package
        uses: actions/upload-artifact@v4 # v4.0.0
        with:
          name: server-build-artifact
          path: server/dist/mattermost-team-linux-amd64.tar.gz
